[2020-11-07 11:30:25] mylog.ERROR: 服务器错误！ ["SQLSTATE[42S02]: Base table or view not found: 1146 Table 'careequiz.user' doesn't exist (SQL: select count(*) as aggregate from `user` where `work_id` = asda)"] []
[2020-11-07 11:32:18] mylog.ERROR: 服务器错误！ ["SQLSTATE[42S02]: Base table or view not found: 1146 Table 'careequiz.user' doesn't exist (SQL: select count(*) as aggregate from `user` where `work_id` = asda)"] []
[2020-11-07 11:33:31] mylog.ERROR: 服务器错误！ ["SQLSTATE[42S02]: Base table or view not found: 1146 Table 'careequiz.user' doesn't exist (SQL: select count(*) as aggregate from `user` where `work_id` = asda)"] []
[2020-11-07 11:34:23] mylog.ERROR: 服务器错误！ ["SQLSTATE[42S02]: Base table or view not found: 1146 Table 'careequiz.user' doesn't exist (SQL: select count(*) as aggregate from `user` where `work_id` = asda)"] []
[2020-11-07 11:35:04] mylog.ERROR: 创建用户失败 ["SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list' (SQL: insert into `login` (`phone`, `password`, `updated_at`, `created_at`) values (asda, $2y$10$v.bX.gsT9.fPtDsMFnrESeerXUIi4UBaqegQrThGQFjgG/aGY18fG, 2020-11-07 11:35:04, 2020-11-07 11:35:04))"] []
[2020-11-07 11:37:56] mylog.ERROR: 创建用户失败 ["SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list' (SQL: insert into `login` (`phone`, `password`, `updated_at`, `created_at`) values (asda, $2y$10$K/b8Tx2NdJsqAu1TWF/DPOjCgA9WYBDjx3x9MzcfHCHd78Yd/I7oq, 2020-11-07 11:37:56, 2020-11-07 11:37:56))"] []
[2020-11-07 11:38:04] mylog.ERROR: 创建用户失败 ["SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list' (SQL: insert into `login` (`phone`, `password`, `updated_at`, `created_at`) values (asd, $2y$10$7iBwCe1z6Y8qXsATASuM7eFvtWdmGzTRDRH75pwbQ44LZNtSFCGre, 2020-11-07 11:38:04, 2020-11-07 11:38:04))"] []
[2020-11-07 11:40:01] mylog.ERROR: 创建用户失败 ["SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list' (SQL: insert into `login` (`phone`, `password`, `updated_at`, `created_at`) values (asd, $2y$10$eYM9Ho3uxhzzV8Pz/crTf.11F0XYzu0sMfyWlrPF.cNKmn2YL1Os., 2020-11-07 11:40:01, 2020-11-07 11:40:01))"] []
[2020-11-07 11:40:03] mylog.ERROR: 创建用户失败 ["SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list' (SQL: insert into `login` (`phone`, `password`, `updated_at`, `created_at`) values (asd, $2y$10$DrCZNPyvkkh2cKEPttoHyORJ7FgQL63u7.R./OXMj4Rhg.2PLo/Xa, 2020-11-07 11:40:03, 2020-11-07 11:40:03))"] []
[2020-11-07 11:40:07] mylog.ERROR: 创建用户失败 ["SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list' (SQL: insert into `login` (`phone`, `password`, `updated_at`, `created_at`) values (asdas, $2y$10$LHtSGAMN2noPd0tD/O2Px.XeE6oFfESG1rq50fYpWUmPOnJZM1GAG, 2020-11-07 11:40:07, 2020-11-07 11:40:07))"] []
[2020-11-07 11:43:03] mylog.ERROR: 服务器错误！ ["Method Illuminate\\Routing\\ResponseFactory::fail does not exist."] []
